# Generated by Django 5.2.12 on 2026-04-02 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('oil_change', 'Oil Change'), ('tire_rotation', 'Tire Rotation'), ('battery_check', 'Battery Check'), ('brake_check', 'Brake Check'), ('engine_check', 'Engine Check'), ('wheel_alignment', 'Wheel Alignment'), ('air_filter_change', 'Air Filter Change')], max_length=20)),
                ('service_date', models.DateField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.vehicle')),
            ],
        ),
    ]
