# Generated by Django 5.2.12 on 2026-04-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_servicebooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('cng', 'CNG')], default='Petrol', max_length=20),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('car', 'Car'), ('bike', 'Bike'), ('scooter', 'Scooter'), ('truck', 'Truck'), ('bus', 'Bus'), ('jeep', 'Jeep'), ('auto', 'Auto')], default='Bike', max_length=20),
        ),
    ]
