# Generated by Django 5.2.12 on 2026-04-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_vehicle_fuel_type_vehicle_vehicle_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='additional_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='pickup_drop',
            field=models.CharField(choices=[('no', 'No'), ('pickup_only', 'Pickup Only'), ('drop_only', 'Drop Only'), ('both', 'Both')], default='no', max_length=20),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='pickup_drop_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='timeslot',
            field=models.CharField(blank=True, choices=[('9-1', '9 AM - 1 PM'), ('1-5', '1 PM - 5 PM'), ('6-10', '6 PM - 10 PM')], max_length=10, null=True),
        ),
    ]
