# Generated by Django 5.2.12 on 2026-04-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_garage_servicebooking_additional_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='garage',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='garage',
            name='lng',
            field=models.FloatField(default=0),
        ),
    ]
