# Generated by Django 5.2.12 on 2026-04-04 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_garage_lat_garage_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='garage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.garage'),
        ),
    ]
