# Generated by Django 5.2.12 on 2026-04-08 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_userprofile_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
